version: '3.8'

services:
  # english-apis:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: english-apis
  #   container_name: english-apis
  #   restart: always
  #   volumes:
  #     - ./dev/logs:/opt/app/logs
  #   ports:
  #     - 3000:3000
  
  mongo:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data/db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - .mongo.env
