enum ConfigKey {
  APP_PORT = 'APP_PORT',
  URL_MONGOOSE = 'URL_MONGOOSE',
  APP_CORS = 'APP_CORS',
  JWT_ACCESS_TOKEN_SECRET_KEY = 'JWT_ACCESS_TOKEN_SECRET_KEY',
  JWT_ACCESS_TOKEN_EXPIRED_IN = 'JWT_ACCESS_TOKEN_EXPIRED_IN',
}

export default ConfigKey;
